### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/infinitezero.net/privkey.pem'

### ISSUE THREAD

**Issue by Lord-Funion** [ProdigyPNP/InfiniteZero#26]
### Describe your issue

When i run pnpm build it does this:

> infinite-zero@3.0.1 build /workspaces/InfiniteZero
> tsc

@Lord-Funion ➜ /workspaces/InfiniteZero (master) $ pnpm start

> infinite-zero@3.0.1 start /workspaces/InfiniteZero
> node dist

[無限零服器] ВКЛЮЧАЕМ СЕРВЕР Infinite Zero...
[無限零服器] ИСПОЛЬЗУЕМ CORS
[無限零服器] ИСПОЛЬЗУЕМ RATE LIMITER
[無限零服器] ДОБАВЛЯЕМ СТРАНИЦУ /index.html...
[無限零服器] ДОБАВИЛИ СТРАНИЦУ /index.html.
[無限零服器] ДОБАВЛЯЕМ СТРАНИЦУ /style.css...
[無限零服器] ДОБАВИЛИ СТРАНИЦУ /style.css.
[無限零服器] ДОБАВЛЯЕМ КАРТИНКУ /favicon...
[無限零服器] ДОБАВИЛИ КАРТИНКУ /favicon.
[無限零服器] ДОБАВЛЯЕМ ФАЙЛ /analytics.json...
[無限零服器] ДОБАВИЛИ ФАЙЛ /analytics.json.
[無限零服器] ДОБАВЛЯЕМ ФАЙЛ /uniques...
[無限零服器] ДОБАВИЛИ ФАЙЛ /uniques.
[無限零服器] ДОБАВЛЯЕМ ФАЙЛ /version...
[無限零服器] ДОБАВИЛИ ФАЙЛ /version.
[無限零服器] ДОБАВЛЯЕМ ФАЙЛ /eval/version...
[無限零服器] ДОБАВИЛИ ФАЙЛ /eval/version.
[無限零服器] ДОБАВЛЯЕМ КОД /eval*...
[無限零服器] ДОБАВИЛИ КОД /eval*.
[無限零服器] ДОБАВЛЯЕМ ДОМЕН /*...
[無限零服器] ДОБАВИЛИ ДОМЕН /*.
[無限零服器] ИСПОЛЬЗУЕМ HTTPS.
node:fs:581
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/infinitezero.net/privkey.pem'
    at Object.openSync (node:fs:581:18)
    at Module.readFileSync (node:fs:457:35)
    at StartServer (file:///workspaces/InfiniteZero/dist/server.js:99:21)
    at file:///workspaces/InfiniteZero/dist/index.js:2:1
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/etc/letsencrypt/live/infinitezero.net/privkey.pem'
}

Node.js v20.11.1
 ELIFECYCLE  Command failed with exit code 1.

### Date of submittion

3/16/24

### Before submitting an issue

- [X] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by afkvido** [comment]
Hi, it seems like you are missing HTTPS SSL certificates on your server/machine.

Look up "lets encrypt, certbot" to get SSL certificates to run this with HTTPS
[You will also need to change the code from the infinitezero.net directory to your domain]

Or, to run without HTTPS (or using a proxy), just take out the code that uses HTTPS
